/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'peter.jamieson' at '9/13/16 2:11 PM' with Gradle 3.0
 *
 * @author peter.jamieson, @date 9/13/16 2:11 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
